// Exact assets exported from Agapay_Website in Figma (YSzodsskD44OjBCaCyBHau).
export const figmaAssets = {
  "map": "/figma/website/map.png",
  "logo": "/figma/website/logo.png",
  "pinNormal": "/figma/website/pinNormal.svg",
  "pinWarning": "/figma/website/pinWarning.svg",
  "pinAdvisory": "/figma/website/pinAdvisory.svg",
  "pinEvacuate": "/figma/website/pinEvacuate.svg",
  "dashboard": "/figma/website/dashboard.svg",
  "stations": "/figma/website/stations.svg",
  "analytics": "/figma/website/analytics.svg",
  "users": "/figma/website/users.svg",
  "health": "/figma/website/health.svg",
  "profile": "/figma/website/profile.svg",
  "settings": "/figma/website/settings.svg",
  "logout": "/figma/website/logout.svg",
  "alerts": "/figma/website/alerts.svg",
  "sos": "/figma/website/sos.svg",
  "rising": "/figma/website/rising.svg",
  "email": "/figma/website/email.png",
  "barangay": "/figma/website/barangay.svg",
  "edit": "/figma/website/edit.svg",
  "account": "/figma/website/account.svg",
  "phone": "/figma/website/phone.svg",
  "calendar": "/figma/website/calendar.svg",
  "location": "/figma/website/location.svg",
  "notifications": "/figma/website/notifications.svg",
  "language": "/figma/website/language.svg",
  "home": "/figma/website/home.svg",
  "about": "/figma/website/about.svg",
  "privacy": "/figma/website/privacy.svg",
  "signout": "/figma/website/signout.svg",
  "google": "/figma/website/google.png",
  "eye": "/figma/website/eye.svg",
  "warning": "/figma/website/warning.svg"
} as const;
